/* ==========================================================================
   DESIGNPILOT AI - PHASE 2E: MULTI-SOURCE INSPIRATION DATASET (js/data.js)
   ========================================================================== */

window.DESIGNPILOT_DATA = {
  // Strict InspirationResult Dataset (Section 5)
  INSPIRATIONS: [
    // ---------------------------------------------------------------------
    // FOOTWEAR & SNEAKER ECOMMERCE (1-10)
    // ---------------------------------------------------------------------
    {
      id: "insp-001",
      title: "KITH Footwear Editorial Experience",
      source: "Awwwards",
      sourceName: "Awwwards",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.awwwards.com/sites/kith-editorial-footwear",
      originalUrl: "https://kith.com",
      previewImage: "https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=400&auto=format&fit=crop",
      description: "High-contrast luxury sneaker storefront featuring full-bleed product photography, micro-interactions, and sticky editorial storytelling.",
      category: "Ecommerce",
      industry: "Footwear",
      style: "Luxury",
      pageType: "Homepage",
      contentType: "website",
      tags: ["Luxury", "Footwear", "Fashion", "Ecommerce", "Sneakers", "Product Page"],
      isDemo: true,
      analysis: "Asymmetrical editorial grid with 60/40 split hero. Neue Haas Grotesk display font paired with JetBrains Mono specs."
    },
    {
      id: "insp-002",
      title: "Nike Sneaker Release Hub",
      source: "Dribbble",
      sourceName: "Dribbble",
      dotClass: "dot-dribbble",
      sourceUrl: "https://dribbble.com/shots/nike-sneaker-release-hub",
      originalUrl: "https://www.nike.com",
      previewImage: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=400&auto=format&fit=crop",
      description: "Sleek urban footwear marketplace with interactive release countdowns and floating 3D product viewports.",
      category: "Ecommerce",
      industry: "Footwear",
      style: "Modern",
      pageType: "Product Listing",
      contentType: "website",
      tags: ["Modern", "Footwear", "Sneakers", "Ecommerce", "Shoe"],
      isDemo: true,
      analysis: "Brutalist street culture meets high-tech 3D product showcase with cyber neon accents."
    },
    {
      id: "insp-003",
      title: "Allbirds Sustainable Footwear Catalog",
      source: "Behance",
      sourceName: "Behance",
      dotClass: "dot-behance",
      sourceUrl: "https://www.behance.net/gallery/allbirds-footwear-catalog",
      originalUrl: "https://www.allbirds.com",
      previewImage: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=400&auto=format&fit=crop",
      description: "Clean minimalist footwear catalog emphasizing eco-friendly wool shoes with subtle natural typography.",
      category: "Ecommerce",
      industry: "Footwear",
      style: "Minimal",
      pageType: "Product Detail",
      contentType: "website",
      tags: ["Minimal", "Footwear", "Shoes", "Ecommerce"],
      isDemo: true,
      analysis: "Soft neutral background palette focusing 100% on shoe texture and material details."
    },
    {
      id: "insp-004",
      title: "Adidas Performance Athletics Store",
      source: "Envato",
      sourceName: "Envato",
      dotClass: "dot-envato",
      sourceUrl: "https://elements.envato.com/performance-athletics-store",
      originalUrl: "https://www.adidas.com",
      previewImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=400&auto=format&fit=crop",
      description: "Performance sports footwear web shop with biomechanical cushioning graphics and runner reviews.",
      category: "Ecommerce",
      industry: "Footwear",
      style: "Bold",
      pageType: "Product Detail",
      contentType: "template",
      tags: ["Bold", "Footwear", "Sports", "Ecommerce", "Running Shoes"],
      isDemo: true,
      analysis: "High contrast red accents driving conversion on technical performance shoes."
    },
    {
      id: "insp-005",
      title: "Haute Couture Footwear Gallery",
      source: "Awwwards",
      sourceName: "Awwwards",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.awwwards.com/sites/haute-fashion-footwear",
      originalUrl: null,
      previewImage: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=400&auto=format&fit=crop",
      description: "Haute couture footwear digital lookbook with runway video loops and instant size reservation sheets.",
      category: "Ecommerce",
      industry: "Footwear",
      style: "Editorial",
      pageType: "Homepage",
      contentType: "website",
      tags: ["Luxury", "Fashion", "Footwear", "Editorial", "Heels"],
      isDemo: true,
      analysis: "Full-bleed video background paired with Didot serif typography."
    },
    {
      id: "insp-006",
      title: "Puma Retro Runner Showcase",
      source: "Web Search",
      sourceName: "Web",
      dotClass: "dot-awwwards",
      sourceUrl: "https://us.puma.com",
      originalUrl: "https://us.puma.com",
      previewImage: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=400&auto=format&fit=crop",
      description: "Dynamic vintage footwear storefront celebrating 80s sneaker silhouettes with retro color blocking.",
      category: "Ecommerce",
      industry: "Footwear",
      style: "Retro",
      pageType: "Homepage",
      contentType: "website",
      tags: ["Retro", "Footwear", "Sneakers", "Ecommerce"],
      isDemo: true
    },
    {
      id: "insp-007",
      title: "On Running Cloud Cushion Experience",
      source: "Awwwards",
      sourceName: "Awwwards",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.awwwards.com/sites/on-running-cloud",
      originalUrl: "https://www.on.com",
      previewImage: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=400&auto=format&fit=crop",
      description: "Swiss engineered running footwear portal with interactive CloudTec soles animation and trail runner stories.",
      category: "Ecommerce",
      industry: "Footwear",
      style: "Minimal",
      pageType: "Landing Page",
      contentType: "website",
      tags: ["Swiss Design", "Footwear", "Minimal", "Running"],
      isDemo: true
    },
    {
      id: "insp-008",
      title: "Vans Customs Sneaker Builder",
      source: "Dribbble",
      sourceName: "Dribbble",
      dotClass: "dot-dribbble",
      sourceUrl: "https://dribbble.com/shots/vans-customs-builder",
      originalUrl: "https://www.vans.com/custom-shoes",
      previewImage: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=400&auto=format&fit=crop",
      description: "Interactive canvas shoe customizer UI allowing real-time pattern placement and sole texture configuration.",
      category: "Ecommerce",
      industry: "Footwear",
      style: "Interactive",
      pageType: "Product Customizer",
      contentType: "ui",
      tags: ["Interactive", "Footwear", "Customizer", "Sneakers"],
      isDemo: true
    },
    {
      id: "insp-009",
      title: "New Balance Heritage Store",
      source: "Web Search",
      sourceName: "Web",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.newbalance.com",
      originalUrl: "https://www.newbalance.com",
      previewImage: "https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=400&auto=format&fit=crop",
      description: "Boston footwear heritage design featuring iconic grey suede 990v5 sneakers with typographic archives.",
      category: "Ecommerce",
      industry: "Footwear",
      style: "Classic",
      pageType: "Homepage",
      contentType: "website",
      tags: ["Classic", "Footwear", "Sneakers", "Ecommerce"],
      isDemo: true
    },
    {
      id: "insp-010",
      title: "Salomon Outdoor Footwear Lab",
      source: "Behance",
      sourceName: "Behance",
      dotClass: "dot-behance",
      sourceUrl: "https://www.behance.net/gallery/salomon-outdoor-footwear",
      originalUrl: "https://www.salomon.com",
      previewImage: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?q=80&w=400&auto=format&fit=crop",
      description: "Technical trail footwear showcase with Gore-Tex waterproofing badges and quicklace mechanism UI.",
      category: "Ecommerce",
      industry: "Footwear",
      style: "Technical",
      pageType: "Product Page",
      contentType: "website",
      tags: ["Technical", "Footwear", "Outdoor", "Trail"],
      isDemo: true
    },

    // ---------------------------------------------------------------------
    // LUXURY & FASHION ECOMMERCE (11-20)
    // ---------------------------------------------------------------------
    {
      id: "insp-011",
      title: "Balenciaga High Fashion Experience",
      source: "Awwwards",
      sourceName: "Awwwards",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.awwwards.com/sites/monolith-fashion",
      originalUrl: "https://www.balenciaga.com",
      previewImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=400&auto=format&fit=crop",
      description: "Avant-garde editorial fashion destination featuring interactive runway video backgrounds and typography masking.",
      category: "Ecommerce",
      industry: "Fashion",
      style: "Luxury",
      pageType: "Homepage",
      contentType: "website",
      tags: ["Luxury", "Fashion", "Editorial", "Ecommerce"],
      isDemo: true
    },
    {
      id: "insp-012",
      title: "Saint Laurent Minimalist Boutique",
      source: "Behance",
      sourceName: "Behance",
      dotClass: "dot-behance",
      sourceUrl: "https://www.behance.net/gallery/saint-laurent-boutique",
      originalUrl: "https://www.ysl.com",
      previewImage: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=400&auto=format&fit=crop",
      description: "Monochrome luxury leather goods and apparel catalog with stark black typography and seamless grid transition.",
      category: "Ecommerce",
      industry: "Fashion",
      style: "Minimal",
      pageType: "Product Listing",
      contentType: "website",
      tags: ["Minimal", "Fashion", "Luxury", "Boutique"],
      isDemo: true
    },
    {
      id: "insp-013",
      title: "Gucci Botanical Capsule Lookbook",
      source: "Awwwards",
      sourceName: "Awwwards",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.awwwards.com/sites/gucci-botanical",
      originalUrl: "https://www.gucci.com",
      previewImage: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=400&auto=format&fit=crop",
      description: "Maximalist luxury fashion experience with animated flora, golden accents, and audio-reactive cursor trails.",
      category: "Ecommerce",
      industry: "Fashion",
      style: "Luxury",
      pageType: "Campaign Page",
      contentType: "website",
      tags: ["Luxury", "Fashion", "Maximalist", "Interactive"],
      isDemo: true
    },
    {
      id: "insp-014",
      title: "Jacquemus Sunlit Provence Lookbook",
      source: "Dribbble",
      sourceName: "Dribbble",
      dotClass: "dot-dribbble",
      sourceUrl: "https://dribbble.com/shots/jacquemus-provence",
      originalUrl: "https://www.jacquemus.com",
      previewImage: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=400&auto=format&fit=crop",
      description: "Warm Mediterranean aesthetic with earthy sand hues, oversized bag showcases, and tactile smooth scroll.",
      category: "Ecommerce",
      industry: "Fashion",
      style: "Minimal",
      pageType: "Homepage",
      contentType: "website",
      tags: ["Minimal", "Fashion", "Editorial", "Handbags"],
      isDemo: true
    },
    {
      id: "insp-015",
      title: "Acne Studios Stockholm Apparel Store",
      source: "Web Search",
      sourceName: "Web",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.acnestudios.com",
      originalUrl: "https://www.acnestudios.com",
      previewImage: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=400&auto=format&fit=crop",
      description: "Swedish brutalist fashion architecture with pastel pink highlights, raw denim textures, and clean column layout.",
      category: "Ecommerce",
      industry: "Fashion",
      style: "Brutalist",
      pageType: "Product Page",
      contentType: "website",
      tags: ["Brutalist", "Fashion", "Denim", "Scandinavian"],
      isDemo: true
    },
    {
      id: "insp-016",
      title: "Off-White Industrial Fashion Hub",
      source: "Envato",
      sourceName: "Envato",
      dotClass: "dot-envato",
      sourceUrl: "https://elements.envato.com/industrial-fashion-hub",
      originalUrl: "https://www.off---white.com",
      previewImage: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=400&auto=format&fit=crop",
      description: "Quotational graphic typography and yellow industrial caution tape aesthetics for streetwear fashion eCommerce.",
      category: "Ecommerce",
      industry: "Fashion",
      style: "Streetwear",
      pageType: "Homepage",
      contentType: "template",
      tags: ["Streetwear", "Fashion", "Graphic", "Bold"],
      isDemo: true
    },

    // ---------------------------------------------------------------------
    // SAAS & DIGITAL PRODUCT DASHBOARDS (21-30)
    // ---------------------------------------------------------------------
    {
      id: "insp-021",
      title: "Linear Issue Tracking & Workflow Suite",
      source: "Awwwards",
      sourceName: "Awwwards",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.awwwards.com/sites/linear-workflow",
      originalUrl: "https://linear.app",
      previewImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=400&auto=format&fit=crop",
      description: "Dark-themed SaaS product design with keyboard shortcut legends, glowing purple gradients, and instant command menus.",
      category: "SaaS",
      industry: "SaaS",
      style: "Dark",
      pageType: "Landing Page",
      contentType: "website",
      tags: ["Dark", "SaaS", "Dashboard", "Productivity"],
      isDemo: true
    },
    {
      id: "insp-022",
      title: "Vercel Cloud Deployment Console",
      source: "Web Search",
      sourceName: "Web",
      dotClass: "dot-awwwards",
      sourceUrl: "https://vercel.com",
      originalUrl: "https://vercel.com",
      previewImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=400&auto=format&fit=crop",
      description: "Understated developer cloud infrastructure dashboard featuring crisp monochrome typography and subtle border glows.",
      category: "SaaS",
      industry: "SaaS",
      style: "Minimal",
      pageType: "Dashboard",
      contentType: "dashboard",
      tags: ["Minimal", "SaaS", "Dashboard", "Developer Tools"],
      isDemo: true
    },
    {
      id: "insp-023",
      title: "Stripe Developer Payments Platform",
      source: "Awwwards",
      sourceName: "Awwwards",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.awwwards.com/sites/stripe-payments-platform",
      originalUrl: "https://stripe.com",
      previewImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=400&auto=format&fit=crop",
      description: "Benchmark SaaS landing page with vibrant multi-layered mesh gradients, interactive code samples, and financial analytics charts.",
      category: "Fintech",
      industry: "Fintech",
      style: "Modern",
      pageType: "Landing Page",
      contentType: "website",
      tags: ["Fintech", "SaaS", "Modern", "Payments"],
      isDemo: true
    },
    {
      id: "insp-024",
      title: "Figma Collaborative Design Workspace",
      source: "Dribbble",
      sourceName: "Dribbble",
      dotClass: "dot-dribbble",
      sourceUrl: "https://dribbble.com/shots/figma-collaborative-workspace",
      originalUrl: "https://www.figma.com",
      previewImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=400&auto=format&fit=crop",
      description: "Vibrant vector design interface with live multiplayer cursor pointers, canvas zoom controls, and component token drawers.",
      category: "SaaS",
      industry: "SaaS",
      style: "Modern",
      pageType: "Product Workspace",
      contentType: "ui",
      tags: ["SaaS", "Design Tool", "Workspace", "UI"],
      isDemo: true
    },
    {
      id: "insp-025",
      title: "Raycast Desktop Intelligence Launcher",
      source: "Behance",
      sourceName: "Behance",
      dotClass: "dot-behance",
      sourceUrl: "https://www.behance.net/gallery/raycast-launcher",
      originalUrl: "https://www.raycast.com",
      previewImage: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=400&auto=format&fit=crop",
      description: "Ultra-fast command palette application landing page with dark glassmorphism and animated extension marketplace grid.",
      category: "SaaS",
      industry: "SaaS",
      style: "Dark",
      pageType: "Landing Page",
      contentType: "website",
      tags: ["Dark", "SaaS", "Glassmorphism", "Productivity"],
      isDemo: true
    },
    {
      id: "insp-026",
      title: "Revolut Business Financial Telemetry",
      source: "Dribbble",
      sourceName: "Dribbble",
      dotClass: "dot-dribbble",
      sourceUrl: "https://dribbble.com/shots/revolut-business-dashboard",
      originalUrl: "https://www.revolut.com/business",
      previewImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=400&auto=format&fit=crop",
      description: "Modern fintech telemetry suite featuring real-time cashflow sparklines, multi-currency card controls, and FX rate widgets.",
      category: "Fintech",
      industry: "Fintech",
      style: "Modern",
      pageType: "Dashboard",
      contentType: "dashboard",
      tags: ["Fintech", "Dashboard", "Banking", "Analytics"],
      isDemo: true
    },

    // ---------------------------------------------------------------------
    // CREATIVE PORTFOLIOS & AGENCIES (31-36+)
    // ---------------------------------------------------------------------
    {
      id: "insp-031",
      title: "Locomotive Creative Agency Portfolio",
      source: "Awwwards",
      sourceName: "Awwwards",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.awwwards.com/sites/locomotive-agency",
      originalUrl: "https://locomotive.ca",
      previewImage: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=400&auto=format&fit=crop",
      description: "Award-winning Montreal digital studio portfolio with kinetic typography, smooth inertial scroll, and interactive WebGL canvas distortion.",
      category: "Agency",
      industry: "Creative",
      style: "Interactive",
      pageType: "Portfolio",
      contentType: "website",
      tags: ["Agency", "Portfolio", "WebGL", "Creative"],
      isDemo: true
    },
    {
      id: "insp-032",
      title: "Resn Immersive Experience Studio",
      source: "Awwwards",
      sourceName: "Awwwards",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.awwwards.com/sites/resn-digital-studio",
      originalUrl: "https://resn.co.nz",
      previewImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=400&auto=format&fit=crop",
      description: "Surreal digital experience studio site with 3D interactive particle fields and sound-reactive WebGL shaders.",
      category: "Agency",
      industry: "Creative",
      style: "Experimental",
      pageType: "Portfolio",
      contentType: "website",
      tags: ["Agency", "3D", "Experimental", "Interactive"],
      isDemo: true
    },
    {
      id: "insp-033",
      title: "Basic® Culture & Craft Agency",
      source: "Behance",
      sourceName: "Behance",
      dotClass: "dot-behance",
      sourceUrl: "https://www.behance.net/gallery/basic-agency-portfolio",
      originalUrl: "https://www.basicagency.com",
      previewImage: "https://images.unsplash.com/photo-1522542550221-31fd19575a2d?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1522542550221-31fd19575a2d?q=80&w=400&auto=format&fit=crop",
      description: "San Diego digital design agency showcasing case studies, brand identity reels, and grid-based editorial case studies.",
      category: "Agency",
      industry: "Creative",
      style: "Bold",
      pageType: "Portfolio",
      contentType: "website",
      tags: ["Agency", "Branding", "Case Study", "Bold"],
      isDemo: true
    },
    {
      id: "insp-034",
      title: "Anton & Irene Brooklyn Design Duo",
      source: "Awwwards",
      sourceName: "Awwwards",
      dotClass: "dot-awwwards",
      sourceUrl: "https://www.awwwards.com/sites/anton-and-irene",
      originalUrl: "https://antonandirene.com",
      previewImage: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=400&auto=format&fit=crop",
      description: "Playful Brooklyn design studio portfolio featuring custom illustrated avatars, parallax timelines, and client project drawers.",
      category: "Portfolio",
      industry: "Creative",
      style: "Playful",
      pageType: "Portfolio",
      contentType: "website",
      tags: ["Portfolio", "Designer", "Illustration", "Creative"],
      isDemo: true
    },
    {
      id: "insp-035",
      title: "Studio Dumbar Visual Identity Lab",
      source: "Web Search",
      sourceName: "Web",
      dotClass: "dot-awwwards",
      sourceUrl: "https://studiodumbar.com",
      originalUrl: "https://studiodumbar.com",
      previewImage: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=400&auto=format&fit=crop",
      description: "Dutch motion branding agency site with kinetic graphic design experiments, poster archives, and video installations.",
      category: "Agency",
      industry: "Creative",
      style: "Graphic",
      pageType: "Portfolio",
      contentType: "website",
      tags: ["Agency", "Motion", "Branding", "Graphic"],
      isDemo: true
    },
    {
      id: "insp-036",
      title: "B&O Beoplay Luxury Sound Showcase",
      source: "Envato",
      sourceName: "Envato",
      dotClass: "dot-envato",
      sourceUrl: "https://elements.envato.com/luxury-sound-showcase",
      originalUrl: "https://www.bang-olufsen.com",
      previewImage: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=1000&auto=format&fit=crop",
      thumbnailImage: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=400&auto=format&fit=crop",
      description: "Danish luxury acoustic hardware experience with anodized aluminum material shaders and spatial sound demos.",
      category: "Ecommerce",
      industry: "Technology",
      style: "Luxury",
      pageType: "Product Detail",
      contentType: "template",
      tags: ["Luxury", "Audio", "Hardware", "Minimal"],
      isDemo: true
    }
  ]
};
